### ISSUE TITLE
General Remarks

### ISSUE THREAD

**Issue by TheMC47** [tony-lang/tree-sitter-tony#317]
Great work @jonhue on tony, it's impressive! :tada: 

That said, I have a couple of remarks:
- **Structure**: Even though the CONTRIBUTING and the CODE_OF_CONDUCT files are well written, they're not referenced in the README. It would've been nice to see them there, as I personally find it more encouraging to contribute. Normally when I glimpse through a github repository, I read the README and I see what follows from it. So linking them there might cause more exposure to the guidelines, and therefore maybe more contributions
- **Content**: The example could've been more detailed. I personally couldn't get anything to execute (yarn complains that `parse` is not found). It also took me a couple of minutes until I found a self-contained "Hello, World!" file in the documentation. That said, here are a couple of suggestions
  - After building the project, maybe mention how to verify that it ran correctly (e.g. by printing the version)
  - Add a step-by-step guide to go through a small example, with each command ran and its respective output. This would help a *newbie* like me who knows almost nothing about TypeScript, NPM, and the related things. 

Again, great work! These are just nitpicking. I see myself turning into a programming languages nerd in the last months, maybe I'll drop by once I know more about TypeScript :smile: 

*Context, for anyone stumbling into this issue when tony becomes big in the future*: https://www21.in.tum.de/teaching/osp/WS20/#activities-1

**Comment by jonhue** [comment]
Thank you so much for your kind words!

I'm sorry about the `yarn parse` problem you encountered. Using this command requires the development setup, just installing with `yarn add tree-sitter-tony` is not enough. The documentation should have been clear on that!

**Comment by TheMC47** [comment]
It works now. Great!
